### ISSUE TITLE
SampleStencil not working on mac docker

### ISSUE THREAD

**Issue by shivasolutions** [IBM-Swift/Kitura-SampleStencil#1]
This sample is not working on mac host with docker, see log attached
[kituraStencil_issue.txt](https://github.com/IBM-Swift/Kitura-SampleStencil/files/204343/kituraStencil_issue.txt)

**Comment by vadimeisenbergibm** [comment]
Blocked by https://github.com/IBM-Swift/Kitura/issues/347, depends on pull request kylef/Stencil#64

**Comment by vadimeisenbergibm** [comment]
@shivasolutions Could you please check the latest code with Swift 3.0?

**Comment by ianpartridge** [comment]
Closing as no response.
