### ISSUE TITLE
Both the develop branch and the master branch cannot build with 2015-04-25-a snapshot of Swift.

### ISSUE THREAD

**Issue by frogcjn** [IBM-Swift/Kitura-SampleStencil#2]
Both the develop branch and the master branch cannot build with 2015-04-25-a snapshot of Swift.

**Comment by vadimeisenbergibm** [comment]
The issue is dependent on https://github.com/kylef/Stencil/issues/66

**Comment by vadimeisenbergibm** [comment]
@frogcjn The master branch works now with Swift 3.0.
